.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EMULATIORS-LAUNCHERS-ESSENCIALS 1 "noviembre 22, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
emulatiors-launchers-essencials \- a set of launchers for huge of emulators
.SH SYNOPSIS
.B consolename
.I "romfilename.ext" 
.br
.B emulatorname
.I "fileimage" ...
.SH DESCRIPTION
This manual page documents briefly the
.B emulatiors-launchers-essencials
specify those 
.B "cosolename"
related command launchers.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBemulators-launchers-essencials\fP is a set of shell invokes and launch a huge 
of related emulators! most knowed!
.SH USAGE
Theres no options, only u must parse the rom game console related to system console emulated name.
.SH LAUNCHERS USAGE AVAILABLES:
In all cases u can use related manpage!
.PP
.B neogeo
.I "romset.ngo"
.br
Neogeo 330Mega laucher for gngeo, must parse the rom set name game "ngo" file, can be a zip file.
.PP
.B neogeopocket
.I "romgame.ngp"
.br
Neogeo Pocket laucher, must parse the rom dumped name game "ngp" file, can be a zip/gz file.
.PP
.B nintendo
.I "romgame.nes"
.br
Nintendo 8bit fceu laucher, must parse the rom dumped name game "nes" file, can be a zip file.
.PP
.B nintendo64
.I "romgame.n64"
.br
Nintendo64 laucher for Mupen64, must parse the rom dumped name game "z64" or "n64" file, can be a zip file.
.PP
.B supernintendo
.I "romgame.smc"
.br
SuperNintendo laucher for snes9x, must parse the rom dumped name game "smc" file, can be a zip file.
.PP
.B ultra64
.I "romgame.n64"
.br
Nintendo64 laucher for Mupen64plus, must parse the rom dumped name game "z64" or "n64" file, can be a zip/gz file.
.PP
.B mastersystem
.I "romgame.sms"
.br
Sega MasterSystem 8bit laucher for osmose, must parse the rom dumped name game "sms" file, can be a zip file.
.PP
.B gamegear
.I "romgame.gg"
.br
Sega GameGear 4bit/8bit laucher for osmose, must parse the rom dumped name game "gg" file, can be a zip file.
.PP
.B gameboy
.I "romgame.gb"
.br
GameBoy 4bit/8bit laucher for vba, must parse the rom dumped name game "gb" file, can be a zip file.
.PP
.B gameboyadvance
.I "romgame.gba"
.br
GameBoy Advance laucher for vba, must parse the rom dumped name game "gba" file, can be a zip/gz file.
.PP
.B gameboycolor
.I "romgame.gbc"
.br
Gameboy Color laucher for vba, must parse the rom dumped name game "gbc" or "cgb" file, can be a zip/gz file.
.PP
.B supergameboy
.I "romgame.sgb"
.br
SuperGameBoy (SNES) laucher for vba, must parse the rom dumped name game "sgb" or "gbc" file, can be a zip/gz file.
.PP
.B pcengine
.I "romgame.pce"
.br
PC-Engine laucher for hugo, must parse the rom dumped name game "pce" file, can be a zip file.
.PP
.B turbografx
.I "romgame.pce"
.br
Turbografx laucher for hugo, must parse the rom dumped name game "pce" file, can be a zip file.
.PP
.B segagenesys
.I "romgame.smd"
.br
Sega Genesis laucher for dgen, must parse the only genesys rom dumped name game "smd" file, not megadrive!
.PP
.B segamegadrive
.I "romgame.smd"
.br
Sega MegaDrive/32X laucher for gens, must parse the megadrive/32x rom dumped name game "smd" or "32x" file!
.PP
.B freedos
.I "filecommand.com"
.br
.B msdos
.I "filecommand.com"
.br
MS-DOS lauchers for dosemu, must parse the command related ".com" file, if not 
the dosemu freedos will be boot and u can use a MS-DOS complete OS emulated!
.SH QEMU LAUNCHERS
A launchers for qemu are provided, for sparc + linux, x86 + linux, arm + linux and x86 + minix , more images are instaled but no launchers are provided, the intention are to stimulate the bash programing usage on normal users!
.SH SEE ALSO
.B neogeo (1) , neogeopocket (1) , neogeocolor (1)
.br
.B nintendo (1) , nintendo64 (1) , supernintendo (1)
.br
.B gameboy (1) , gameboycolor (1) , gameboyadvance (1) , supergameboy (1)
.br
.B segagenesys (1) , dreamcast (1) , segasaturn (1) 
.br
.B segagamegear (1) , segamastersystem (1), segamegadrive (1)
.br
.B qemucdrom (1) , qemulinux (1) , qemuminix (1) , qemusparc (1)
.br
.SH AUTHOR
emulators-launchers-essencials its mantained by PICCORO Lenz McKAY 
\fI<mckaygerhard@gmail.com>\fP and the McKAY emu team \fI<qgqlochekone@gmail.com>\fP 
qith colaboration of \fBsebb\fP for the VENENUX GNU/Linux proyect under GPL license!
.PP
This manual page was written by PICCORO Lenz McKAY \fI<mckaygerhard@gmail.com>\fP,
for the VENENUX GNU/Linux project (but may be used by others).
